### ISSUE TITLE
compatibility with ros2(humble in my case) 

### ISSUE THREAD

**Issue by Bhargav-CS** [eborghi10/Hexapod-ROS#3]
I want to know how I can use this repo to work with ros2 (humble). Since I am using ubuntu 22.04, I also need to take care of migrations and build dependencies.

**Comment by eborghi10** [comment]
Hi @Bhargav-CS, this repository is not actively maintained so if you want to use it with ROS 2, you'll need to migrate it yourself. You can take a look at [this official Humble documentation](https://docs.ros.org/en/humble/How-To-Guides/Migrating-from-ROS1.html) to know how to do it.
